### ISSUE TITLE
QALB

### ISSUE THREAD

**Issue by saloyiana** [CAMeL-Lab/arabic_error_type_annotation#1]
Dears, 
I am trying to contact you to get more info regards the QALB dataset (the one used in this project).  Is there any preferred channel to get the needed answers through? 

Sorry if this is a wrong place to ask such questions.

**Comment by nizarhabash1** [comment]
Hi - Thanks for reaching out. The data will be released soon (before the end of November, 2021).

**Comment by nizarhabash1** [comment]
Hi - We just released the data -- https://twitter.com/CamelNlp/status/1466769542169116676
